services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: crabchat
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres"]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus