services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: crabchat
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres"]